<h1>FEDERICA</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quis fringilla mi. Proin egestas odio eget eros tincidunt ornare. Mauris ornare tristique suscipit. Sed sodales, nunc ut sagittis semper, felis diam porta ipsum, sit amet suscipit odio lacus id risus. Sed luctus porttitor semper. Nullam pharetra tincidunt orci, et luctus odio aliquam ut. Cras sed quam lectus, a gravida velit. Praesent vel purus lectus. Proin tristique lectus id elit pulvinar quis porta lacus porttitor. Proin ultrices tempor mauris eget suscipit. Nulla tellus mi, laoreet vel molestie a, congue in lectus. Ut non ipsum eros. Morbi pharetra lobortis lectus, nec blandit arcu euismod sed. Nulla eget enim lacus. Morbi commodo ullamcorper lacinia.</p>
<p>Cras nulla diam, consequat quis malesuada non, tincidunt non nisl. Pellentesque ac rhoncus erat. Donec adipiscing venenatis iaculis. Integer id justo nisi. Donec rhoncus tincidunt sem, ac semper odio auctor at. Mauris pellentesque neque et mauris malesuada gravida. Phasellus gravida velit id risus suscipit ac auctor dui hendrerit. Curabitur euismod ante a risus lobortis suscipit. Nunc diam turpis, lacinia vel blandit vel, elementum quis nisi. Donec placerat tellus id eros porttitor luctus. Aliquam erat volutpat. Duis non nulla eget lacus gravida placerat. Aliquam malesuada semper varius. Vestibulum eu augue sapien, ac consequat tellus. Pellentesque imperdiet ante vitae ligula malesuada a iaculis orci dapibus. Nullam egestas ultrices lorem ut pellentesque.</p>
<p>Mauris eu justo leo. Fusce nec nibh metus, a pharetra nisi. Morbi at metus metus. Phasellus ultricies, tortor ut consectetur eleifend, ligula mi convallis nisi, vel commodo metus ligula id lacus. Cras ligula felis, feugiat quis tincidunt sit amet, convallis ac risus. Maecenas pellentesque cursus augue, sed commodo nulla mollis ut. Vivamus imperdiet malesuada venenatis. Quisque at eros arcu, eu blandit quam. Duis ac tellus mi, sit amet dignissim risus. Suspendisse semper malesuada justo, sagittis egestas risus consequat et. Donec egestas mattis sem, eu consectetur dolor fringilla eu.</p>
<p>Phasellus in sem lectus, nec mattis dui. Phasellus fringilla lectus sed ligula aliquet vel fermentum tortor vehicula. Nam et urna ac dolor pharetra ultrices ac ut mi. Nulla non cursus purus. Pellentesque justo felis, elementum a venenatis ut, aliquam quis metus. Morbi odio velit, dapibus vitae placerat nec, ultricies pellentesque nisl. Sed at sapien et tellus tempus iaculis eget in arcu. Aenean dignissim bibendum sodales.</p>
<p>Vestibulum condimentum, nunc vitae aliquet faucibus, orci magna dignissim urna, ut iaculis justo diam vel mi. Vivamus faucibus cursus lacinia. Nullam pharetra leo ut neque egestas laoreet. Quisque tempus elementum ipsum. In aliquam auctor aliquet. Sed at risus eros. Sed rhoncus, metus sed tincidunt ornare, eros sem bibendum nisl, convallis sollicitudin nulla nunc in arcu. In facilisis convallis pharetra. Fusce et augue commodo urna interdum consectetur id nec nibh. Duis laoreet sollicitudin orci sed ultrices. Nullam vitae diam libero. Donec rutrum, magna eu adipiscing ultrices, nisi tortor euismod nisl, eu condimentum eros ante vel purus. Aenean augue odio, eleifend at vulputate ut, placerat quis elit. Sed egestas vestibulum diam vel tristique. Praesent molestie elit quis sapien varius rhoncus. Morbi sed mauris vel elit rutrum tincidunt id at purus. </p>
<ul>
    <li><a href="<?php echo $this->url(array(), 'base') ?>">página de inicio (mi mismo)</a></li>
    <li><a href="<?php echo $this->url(array(), 'base_error') ?>">página de error</a></li>
    <li><a href="<?php echo $this->url(array(), 'base_confirm') ?>">página de confirmación</a></li>
</ul>
<p>En este mundo, donde las cosas duran un pestañeo, todos (incluso yo) se
preguntarán: ¿Cúal es la utilidad de un sistema que solo muestra tres páginas
absolutamente inutiles?</p>
<p>Pues bien, yo siempre digo:</p>
<blockquote>"todas las cosas son la misma cosa, y por tanto todas las cosas estan
reflejadas en las demas cosas"</blockquote>
<p>Este sistema es uno mas de mis intentos de demostrar esta teoria.</p>
